// action types
export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const GET_LOGGED_USER_RESPONSE = 'GET_LOGGED_USER_RESPONSE';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const SET_USER_LOGIN_RESPONSE = 'SET_USER_LOGIN_RESPONSE';
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT';
export const SET_USER_LOGOUT_RESPONSE = 'SET_USER_LOGOUT_RESPONSE';
